// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionAnalysisBackend;

#nullable disable

namespace ProductionAnalysisBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118160654_AddParameters")]
    partial class AddParameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Deviation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReasonGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RowId")
                        .HasColumnType("integer");

                    b.Property<string>("TakenMeasures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReasonGroupId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("RowId");

                    b.HasIndex("UserId");

                    b.ToTable("Deviation");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.DownTimeReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsobility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DownTimeReasons");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PowerPerHour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.HourlyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("CumulativeActual")
                        .HasColumnType("integer");

                    b.Property<int>("CumulativePlan")
                        .HasColumnType("integer");

                    b.Property<int>("Deviation")
                        .HasColumnType("integer");

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("HourInterval")
                        .HasColumnType("integer");

                    b.Property<int>("PlanQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("HourlyDates");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.LongCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ActualStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("DeviationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlanEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlanStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("LongCycles");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.MultiplyProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("ChangeOverTime")
                        .HasColumnType("integer");

                    b.Property<int>("CycleTime")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTempo")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("MultiplyProductions");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeOverMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CleaningMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CycleTimeSec")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTarget")
                        .HasColumnType("integer");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPerHour")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("TaktTimeSec")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MultiplyProductionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MultiplyProductionId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendToReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ProductionAnalyses");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReasonGroupId");

                    b.ToTable("Reason");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ReasonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReasonGroup");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("FactCumulative")
                        .HasColumnType("integer");

                    b.Property<int>("FactQTY")
                        .HasColumnType("integer");

                    b.Property<int>("PlanCumulative")
                        .HasColumnType("integer");

                    b.Property<int>("PlanQTY")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkIntervalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionAnalysisId");

                    b.HasIndex("WorkIntervalId");

                    b.ToTable("Row");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeoverMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CleaningMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.WorkInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("WorkIntervals");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Comment", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany("Comments")
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Deviation", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ReasonGroup", "ReasonGroup")
                        .WithMany("PADeviations")
                        .HasForeignKey("ReasonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Reason", "Reason")
                        .WithMany("Deviations")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Row", "Row")
                        .WithMany("Deviations")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reason");

                    b.Navigation("ReasonGroup");

                    b.Navigation("Row");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Equipment", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", null)
                        .WithMany("Equipments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.HourlyData", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.LongCycle", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.MultiplyProduction", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Parameter", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany("Parameters")
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.MultiplyProduction", null)
                        .WithMany("Products")
                        .HasForeignKey("MultiplyProductionId");

                    b.HasOne("ProductionAnalysisBackend.Models.Scenario", null)
                        .WithMany("Products")
                        .HasForeignKey("ScenarioId");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "Operator")
                        .WithMany("ProductionAnalyses")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Operator");

                    b.Navigation("Scenario");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ReasonGroup", "ReasonGroup")
                        .WithMany("Reasons")
                        .HasForeignKey("ReasonGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReasonGroup");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Product", "Product")
                        .WithMany("Rows")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.WorkInterval", "WorkInterval")
                        .WithMany()
                        .HasForeignKey("WorkIntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionAnalysis");

                    b.Navigation("WorkInterval");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Setting", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Shift", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "Operator")
                        .WithMany("Shifts")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.WorkInterval", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Department", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.MultiplyProduction", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ReasonGroup", b =>
                {
                    b.Navigation("PADeviations");

                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Scenario", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProductionAnalyses");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
