// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionAnalysisBackend;

#nullable disable

namespace ProductionAnalysisBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119102315_AddFieldsToOPerations")]
    partial class AddFieldsToOPerations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.CycleOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("FactDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PlanQty")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionCycleAnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionCycleAnalysisId");

                    b.ToTable("CycleOperations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Deviation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ReasonGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RowId")
                        .HasColumnType("integer");

                    b.Property<string>("TakenMeasures")
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReasonGroupId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("RowId");

                    b.ToTable("Deviations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PowerPerHour")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeOverMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CleaningMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("CycleTimeSec")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTarget")
                        .HasColumnType("integer");

                    b.Property<int>("LunchBreakMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPerHour")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("TaktTimeSec")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendToReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ProductionAnalyses");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionCycleAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductionCycleAnalyses");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ReasonGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReasonGroups");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DowntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("FactCumulative")
                        .HasColumnType("integer");

                    b.Property<int>("FactQTY")
                        .HasColumnType("integer");

                    b.Property<int>("PlanCumulative")
                        .HasColumnType("integer");

                    b.Property<int>("PlanQTY")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkIntervalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionAnalysisId");

                    b.HasIndex("WorkIntervalId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.WorkInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductionAnalysisId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductionAnalysisId");

                    b.ToTable("WorkIntervals");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Comment", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany("Comments")
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.CycleOperation", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionCycleAnalysis", "ProductionCycleAnalysis")
                        .WithMany("Operations")
                        .HasForeignKey("ProductionCycleAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionCycleAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Deviation", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ReasonGroup", "ReasonGroup")
                        .WithMany("Deviations")
                        .HasForeignKey("ReasonGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Reason", "Reason")
                        .WithMany("Deviations")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Row", "Row")
                        .WithMany("Deviations")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reason");

                    b.Navigation("ReasonGroup");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Equipment", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", null)
                        .WithMany("Equipments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Parameter", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany("Parameters")
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Scenario", null)
                        .WithMany("Products")
                        .HasForeignKey("ScenarioId");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "Operator")
                        .WithMany("ProductionAnalyses")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Product", "Product")
                        .WithMany("ProductionAnalysis")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("Scenario");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionCycleAnalysis", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Operator");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ReasonGroup", "ReasonGroup")
                        .WithMany("Reasons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReasonGroup");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Product", "Product")
                        .WithMany("Rows")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany("Rows")
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.WorkInterval", "WorkInterval")
                        .WithMany()
                        .HasForeignKey("WorkIntervalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionAnalysis");

                    b.Navigation("WorkInterval");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Shift", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductionAnalysisBackend.Models.User", "Operator")
                        .WithMany("Shifts")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.WorkInterval", b =>
                {
                    b.HasOne("ProductionAnalysisBackend.Models.ProductionAnalysis", "ProductionAnalysis")
                        .WithMany()
                        .HasForeignKey("ProductionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionAnalysis");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Department", b =>
                {
                    b.Navigation("Equipments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Product", b =>
                {
                    b.Navigation("ProductionAnalysis");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionAnalysis", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Parameters");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ProductionCycleAnalysis", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Reason", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.ReasonGroup", b =>
                {
                    b.Navigation("Deviations");

                    b.Navigation("Reasons");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Row", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.Scenario", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductionAnalysisBackend.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProductionAnalyses");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
